////
Javascript dev enviroment setup. The parent document should use this content by:
=== Javascrip dev environment setup
include::../docs/js-dev-setup.adoc[]

Normally the above would expand the content of this file inside the parent doc. 
But GitHub doesn't support Asciidoc include file: https://github.com/github/markup/issues/1095
The included file is just rendered as a link.
////

=== Javascript dev environment for Cloudstate

* Install https://www.docker.com/get-started[Docker]
** Check with `docker version`, version v19.03+ recommended
* Install https://github.com/nvm-sh/nvm#install--update-script[nvm] (node version manager)
** Check with `nvm --version`, version 0.34.0+ recommended
* Install https://www.npmjs.com/get-npm[npm] (node package manager)
** Check with `npm -v`, version 6.14.3+ recommended
* Install the protobuf compiler.
    ** Check with `protoc --version`, version 3.0.0+ recommended
    ** Mac OS X `brew install protobuf`
    ** Linux `sudo apt install protobuf-compiler`
    ** Or https://developers.google.com/protocol-buffers/docs/downloads[alternatively] (src and bins)


=== gRPCurl for testing GRPC servers

The communication between the Cloudstate `user-function` uses the gRPC protocol. https://github.com/fullstorydev/grpcurl[gRPCurl] is a command-line tool allowing to query gRPC servers in the same fashion as `curl` with REST servers. 

https://github.com/fullstorydev/grpcurl#installation[Install gRPCurl] from `brew` if you are on MacOS or directly from binaries for other OS. If the installation is successful, you should be able to invoke `grpcurl -version` in a terminal:

[source,shell]
----
$ grpcurl -version
grpcurl 1.6.0
----
